# Generated by Django 2.2.6 on 2019-10-26 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='origin',
            field=models.ImageField(default='images/userimages/dafault_image.png', upload_to='images/userimages/'),
        ),
        migrations.AlterField(
            model_name='akeet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 14, 11, 16, 570134, tzinfo=utc)),
        ),
    ]
