# Generated by Django 2.2.6 on 2019-10-21 21:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akeet',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='akitter.Akeet'),
        ),
        migrations.AlterField(
            model_name='akeet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 21, 39, 58, 477951, tzinfo=utc)),
        ),
    ]
