# Generated by Django 2.2.6 on 2019-10-21 21:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akitter', '0002_auto_20191022_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akeet',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='akitter.Akeet'),
        ),
        migrations.AlterField(
            model_name='akeet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 21, 42, 3, 402656, tzinfo=utc)),
        ),
    ]
