# Generated by Django 2.2.6 on 2019-10-26 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akitter', '0002_auto_20191026_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='origin',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='userimages/default_image.png', upload_to='userimages/'),
        ),
        migrations.AlterField(
            model_name='akeet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 5, 24, 711060, tzinfo=utc)),
        ),
    ]
