# Generated by Django 2.2.6 on 2019-10-26 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akitter', '0003_auto_20191027_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akeet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 22, 31, 138526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='images/userimages/default_image.png', upload_to='images/userimages/'),
        ),
    ]
