# Generated by Django 2.2.6 on 2019-10-26 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('akitter', '0004_auto_20191027_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='image',
            new_name='origin',
        ),
        migrations.AlterField(
            model_name='akeet',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 20, 24, 12, 771632, tzinfo=utc)),
        ),
    ]
